import React from 'react'
import Footer from '../Footer/Footer'
import Header from '../Header/Header'

const Refunds = () => {
  return (
      <>
      <Header />
      <main id="page-content" className="">

<section className="header header-backdrop header-backdrop-blue-green position-relative overflow-hidden"><div className="container">
<div className="d-none d-md-block sprite sprite-circle-bottom" style={{position: 'absolute', top: '50%', left: 0, color: '#E7F5F8', opacity: 0.5}}></div>
  <h1>
    Refund Policy
  </h1>
</div></section>
<div className="container mb-5" style={{maxWidth: 720}}>
  <div className="card card-with-shadow text-layout-card">
    <div className="card-body">

      <p style={{fontWeight: 'bold'}} className="mt-4">
        If you are not 100% satisfied with your purchase, please <a href="/support/contact">contact us</a>.
      </p>

      <h2>
        14 Days Money Back Guarantee
      </h2>

      <p>
  The 14 Days Money Back Guarantee applies if ...
</p>

<ol>
  <li>
    you have purchased a subscription for the first time,
  </li>
  <li>
    the subscription was purchased within the last 14 days,
  </li>
  <li>
    you are not satisfied with the result quality and have no use for cut out images generated by offbg.com,
  </li>
  <li>
    you have processed a total of less than 50 images in any resolution, and
  </li>
  <li>
    your account, you personally and your company have not made use of the 14 Days Money Back Guarantee before.
  </li>
</ol>

      <p>
        To place a refund request, you would have to fill out <a href="/refunds/new">this form</a>. We will then review your request within 10 days and contact you via email.
      </p>

      <h2>
        Other Refunds
      </h2>

      <p>
        Purchases outside of the 14 Days Money Back Guarantee are generally non-refundable. If you are unhappy with your subscription you can <a href="/dashboard">cancel it</a> any time. If you have any questions, feel free to <a href="/support">contact us</a>.
      </p>
    </div>
  </div>
</div>

  </main>
      <Footer />
      </>
  )
}

export default Refunds